name: Python CI

on: push

jobs:
  build:

    runs-on: ubuntu-18.04
    container: pcic/geospatial-python:gdal3

    strategy:
      matrix:
        python-version: [3.8]
    env:
      PIP_INDEX_URL: https://pypi.pacificclimate.org/simple

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apk add libxml2-dev libxslt-dev
        pip install -U pip wheel
        pip install -r requirements.txt -r test_requirements.txt
        pip install .
    - name: Test with pytest
      run: |
        pytest -v --cov --flake8
