name: Python CI

on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            libpq-dev \
            libhdf5-dev \
            libnetcdf-dev \
            gdal-bin \
            libgdal-dev \
            libproj-dev \
            proj-data \
            libgeos-dev

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Install project dependencies (including test extras)
        env:
          CPLUS_INCLUDE_PATH: /usr/include/gdal
          C_INCLUDE_PATH: /usr/include/gdal
        run: poetry install --extras "test"

      - name: Test with pytest (full)
        if: github.ref == 'refs/heads/master'
        run: poetry run pytest tests/ -m "not online" --cov --cov-report term-missing

      - name: Test with pytest (fast)
        if: github.ref != 'refs/heads/master'
        run: poetry run pytest -m "not slow and not online"
